### ISSUE TITLE
add gaw

### ISSUE THREAD

**Issue by mattvenn** [TinyTapeout/analog-virtualbox-vm-sky130a#1]
https://www.rvq.fr/php/ndl.php?id=gaw.?-.*

needs lib-gtk3-dev

http://web02.gonzaga.edu/faculty/talarico/vlsi/xschemInstall.html

**Comment by mattvenn** [comment]
also needs the .gaw/gawrc server port changed
![image](https://github.com/TinyTapeout/analog-virtualbox-vm-sky130a/assets/634220/f091b31b-6537-4256-91c7-8ccc6e5bf10a)

**Comment by urish** [comment]
Not sure about the .gawrc bit - let's wait for the [current run](https://github.com/TinyTapeout/analog-virtualbox-vm-sky130a/actions/runs/8193398996) to finish, then just write down the commands that you need to run to configure `.gaw/gawrc` correctly in the VM, and we can add them to the setup script.

**Comment by urish** [comment]
VM build passed: https://github.com/TinyTapeout/analog-virtualbox-vm-sky130a/actions/runs/8196432470
