### ISSUE TITLE
xschem needs a HEAD version for compatibility with selected PDK version

### ISSUE THREAD

**Issue by algofoogle** [TinyTapeout/analog-virtualbox-vm-sky130a#3]
Current manifest includes [xschem 3.4.4](https://github.com/TinyTapeout/analog-virtualbox-vm-sky130a/blob/3e18d029f6ee58083c25ab18aed94044aa7f1a19/image.pkr.hcl#L83) but I've noticed that the chosen recent [PDK version `bdc9412`](https://github.com/TinyTapeout/analog-virtualbox-vm-sky130a/blob/3e18d029f6ee58083c25ab18aed94044aa7f1a19/image.pkr.hcl#L78) relies on a newer (pre-release) version of xschem 3.4.5 in order to fully support this (e.g. to get all graphs working in the test_env example).

Existing guides don't differentiate currently and just go with the HEAD commit (latest in `master`). I guess we could set `XSCHEM_VERSION` to `master` or a known good that is recent enough (currently `659231e7ae06c745caa6e1776cceca0c1afe7322` seems fine?)

(Unimportant, but I also just noticed a tiny typo [in the install_xschem.sh script](https://github.com/TinyTapeout/analog-virtualbox-vm-sky130a/blob/3e18d029f6ee58083c25ab18aed94044aa7f1a19/scripts/install_xschem.sh#L29) with the keyword "simu***al***tion")

**Comment by urish** [comment]
Let's go with a specific commit - we want reproducible builds :) Thanks!

**Comment by urish** [comment]
@StefanSchippers any plans to cut 3.4.5 sometime soon?

**Comment by StefanSchippers** [comment]
I will work on this. Will restrict commits to bug-fix only and if no regression pops up will tag 3.4.5

**Comment by urish** [comment]
@mattvenn implemented a workaround at e0e6790
